-- Creo Base de Datos
CREATE DATABASE lupulus;
-- Uso Base de Datos
USE  lupulus;

-- Creo tabla de Usuario
CREATE TABLE usuario(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(50),
  apellido VARCHAR(50),
  email VARCHAR(100) NOT NULL UNIQUE,
  direccion VARCHAR(50),
  ciudad VARCHAR(50),
  provincia VARCHAR(50),
  telefono VARCHAR(30),
  avatar VARCHAR(255),
  pass VARCHAR(255) NOT NULL,
  tipoCons VARCHAR(255),
  rol_id INT
);

-- Creo tabla de Roles

CREATE TABLE rol(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  usuario_id INT
);

-- Creo tabla de Tipo Consumidor
CREATE TABLE tipoCons(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  usuario_id INT
);

-- Creo tabla Provincia
CREATE TABLE provincia(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  usuario_id INT
);

-- Creo tabla Ciudad
CREATE TABLE ciudad(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  provincia_id INT
);

-- Creo tabla Avatar
CREATE TABLE avatar(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  usuario_id INT
);

-- Creo tabla Categoria
CREATE TABLE categoria(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50)
);

-- Creo tabla Producto
CREATE TABLE producto(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  descripcion VARCHAR(500),
  precio FLOAT(10,2) NOT NULL,
  stock INT NOT NULL,
  categoria_id INT,
  subcategoria_id INT,
  estado INT NOT NULL,
  borrado INT
);

-- Creo tabla Subcategoria
CREATE TABLE subcategoria(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  categoria_id INT
);

-- Creo tabla Imagen
CREATE TABLE imagen(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  producto_id INT
);

-- Creo tabla Envio
CREATE TABLE envio(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50),
  estado VARCHAR(50),
  venta_id INT
);

-- Creo tabla Venta
CREATE TABLE venta(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  formaDePago VARCHAR(50),
  estado VARCHAR(50),
  envio_id INT,
  producto_id INT,
  usuario_id INT
);

-- Creo tabla Pago
CREATE TABLE pago(
  id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
  estado VARCHAR(50),
  venta_id INT
);

-- Creo tabla Venta-Producto
CREATE TABLE venta_producto(
  precioDelDia INT DEFAULT NULL,
  cantidadProducto INT DEFAULT NULL,
  producto_id INT,
  venta_id INT
);


-- Agrego las claves foraneas de cada tabla

ALTER TABLE usuario ADD FOREIGN KEY (rol_id) REFERENCES rol(id);
ALTER TABLE rol ADD FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE tipoCons ADD FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE provincia ADD FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE ciudad ADD FOREIGN KEY (provincia_id) REFERENCES provincia(id);
ALTER TABLE avatar ADD FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE producto ADD FOREIGN KEY (categoria_id) REFERENCES categoria(id);
ALTER TABLE producto ADD FOREIGN KEY (subcategoria_id) REFERENCES subcategoria(id);
ALTER TABLE subcategoria ADD FOREIGN KEY (categoria_id) REFERENCES categoria(id);
ALTER TABLE imagen ADD FOREIGN KEY (producto_id) REFERENCES producto(id);
ALTER TABLE envio ADD FOREIGN KEY (venta_id) REFERENCES venta(id);
ALTER TABLE venta ADD FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE venta ADD FOREIGN KEY (producto_id) REFERENCES producto(id);
ALTER TABLE venta ADD FOREIGN KEY (envio_id) REFERENCES envio(id);
ALTER TABLE pago ADD FOREIGN KEY (venta_id) REFERENCES venta(id);
ALTER TABLE venta_producto ADD FOREIGN KEY (producto_id) REFERENCES producto(id);
ALTER TABLE venta_producto ADD FOREIGN KEY (venta_id) REFERENCES venta(id);

-- Agrego Roles
INSERT INTO rol (id, nombre) VALUES (null, 'administrador'), (null, 'cliente'), (null, 'editor'),
(null, 'proveedor'), (null, 'distribuidor'), (null, 'vendedor');

-- Agrego Tipo de Consumidor
INSERT INTO tipoCons (id, nombre) VALUES (null, 'Consumidor Final'), (null, 'IVA Responsable Inscripto'),
(null, 'IVA Responsable No Inscripto'), (null, 'IVA Sujeto Exento');

-- Agrego Categorias
INSERT INTO categoria (id, nombre) VALUES (null,'Equipamiento'),(null,'Insumos'),(null,'Kit');

-- Agrego Sub-Categorias
INSERT INTO subcategoria (id, nombre, categoria_id) VALUES (null,'Canillas y conectores',1),(null,'Embarrillado',1),(null,'Embotellado',1),
(null,'Enfriado',1),(null,'Fermentacion',1),(null,'Macerado y hervido',1),(null,'Mangueras',1),(null,'Medicion y control',1),
(null,'Molienda',1),(null,'Tratamiento agua',1),(null,'Azucares',2),(null,'Botellas',2),(null,'Clarificantes',2),(null,'Correccion agua',2),
(null,'Levaduras',2),(null,'Limpieza',2), (null,'Lúpulus',2),(null,'Maltas',2),(null,'Tapas',2),(null,'Kit equipos',3),(null,'Kit insumos',3);

-- Agrego Productos
INSERT INTO producto(id, nombre, descripcion, stock, subcategoria_id, estado, precio) VALUES
 (null,' CONECTOR RECTO ROSCA MACHO','ACOPLE CONECTOR RECTO ROSCA MACHO 1/4',13,1,1,227.43),
 (null,'CANILLA CHOP PLASTICA','CANILLA TIPO CHOPP AMERICANA MANUAL PARA CORNELIUS-BARRIL ',17,1,1,353.80),
 (null,'CANILLA DOBLE ACCION','CANILLA DOBLE ACCION PARA CHOPERA ',9,1,1,2879.50),
 (null,' BARRIL PET ','BARRIL CAPACIDAD 30 LTS. ESTIVADO 4X4 HASTA 3 PISOS',3,2,1,784.01),
 (null,'ADAPTADOR ROSCA HEMBRA BRONCE','BUJE BRONCE ADAPTADOR PARA TUERCA CANILLAS ',15,2,1,396.40),
 (null,'GASIFICADORA ESTÁTICA','SISTEMA DE GASIFICACION DE CERVEZA COMPACTO ',4,2,1,11555.57),
 (null,' BIDON EMBOTELLADOR ','BIDON DE 25 LITROS PARA MADURAR/ FERMENTAR CON CANILLA',78,3,1,414.06),
 (null,'LAVADOR DE BOTELLAS','DISPOSITIVO QUE SE ENROSCA EN CANILLA DE 1/2 Y SE ACCIONA PRESION DE LA BOTELLA ',22,3,1,582.01),
 (null,'GLLENADORA ALTO FLUJO','VARILLA CON VALVULA DOSIFICADORA QUE PERMITE LLENAR BOTELLAS HASTA EL CUELLO ',11,3,1,371.35),
 (null,' ENFRIADOR CONTRACORRIENTE ','ENFRIADOR CONTRACORRIENTE DE ALUMINIO',22,4,1,1922.91),
 (null,'SERPENTINA CHOPERA','SERPENTINA CHOPERA 15M ',34,4,1,2642.29),
 (null,'SERPENTINA INMERSION M','SERPENTINA INMERSION 7M ',19,4,1,1204.88),
 (null,' ACIDO CITRICO ','GRADO ALIMENTICIO, PARA REGULAR EL PH DE MACERACIÓN',21,5,1,330.46),
 (null,'ACOPLE RAPIDO HEMBRA','ACOPLE RAPIDO PP PARA MANGUERA 1/2 PULGADA',22,5,1,527.56),
 (null,'ACOPLE RAPIDO MACHO','ACOPLE RAPIDO PARA OLLA. 1/2 PULGADA ',23,5,1,169.40),
 (null,' BOLSA MACERADORA ','ASEGURAR UNA MACERACIÓN EFICIENTE Y PARA PERMITIR EL ACLARADO, ADEMÁS DE PARA DRENAR BIEN EL MOSTO DESPUÉS DEL MACERADO Y LA COCCIÓN.',24,6,1,139.66),
 (null,'BOMBA TRASVASE GRUNDFOS','BOMBA TRASVASE RECOMENDADA PARA EQUIPOS DE 50  HASTA 500 LITROS',25,6,1,11313.50),
 (null,'ESTRUCTURA PARA 3 OLLAS','ESTRUCTURA PARA OLLAS CON UN DESNIVEL PARA EQUIPOS DE 50 A 100L. ',26,6,1,7365.59),
 (null,'MANGUERA TEJIDA','MANGUERA TEJIDA, SOPORTA PRESION, ES SANITARIA, IDEAL TRASVASE, CARBONATAR.',26,7,1,76.63),
 (null,'BALANZA DIGITAL','HASTA 7 KG (MIDE GR X GR).CUERPO DE PLÁSTICO ABS. PESA EN GRAMOS Y ONZAS.FUNCIÓN DE TARA Y CALIBRACIÓN.',27,8,1,835.97),
 (null,'DENSIMETRO','DENSÍMETRO.ESCALA DE GRAVEDAD ESPECÍFICA DE 1000 A 1100.',28,8,1,708.62),
 (null,'PROBETA PLASTICA','PROBETA PLASTICA PARA DENSIMETRO.',29,8,1,292.22),
 (null,'MOLINO A DISCO','EXACTA PROPORCIÓN DE HARINA FINA, HARINA GRUESA Y CASCARA.TOLVA DE FUNDICIÓN INTEGRADA AL CUERPO.',28,9,1,4671.81),
 (null,'MOLINO A RODILLO PARA TALADRO','RODILLOS 6 CM DE LARGO.MUELE 100 KG HORA.PARA USO CON TALADRO.IDEAL PARA MOTORIZAR.',29,9,1,10182.15),
 (null,'MOLIENDA MALTAS BASE ','LA COMPRA DE ESTE PRODUCTO DEBE SER CON UNA ANT. MINIMA DE 24HS Y COORDINAR CON PRODUCCION EL RETIRO DE LA MISMA.',30,9,1,100.00),
 (null,'CARCAZA PARA FILTRO',' CARCAZA PARA FILTRO. ',31,10,1,1845.53),
 (null,' FILTRO CARBON ACTIVADO ',' FILTRO PARA COLOCAR EN CARCAZA.',32,10,1,1475.05),
 (null,'AZUCAR DE MAIZ',' AZÚCAR OBTENIDA DE LA HIDRÓLISIS ENZIMÁTICA DE ALMIDONES DE MAIZ Y OTROS CEREALES. ',32,11,2,183.15),
 (null,' FLACTOSA ',' AZÚCAR NO FERMENTABLE QUE OTORGA CUERPO Y DULZOR A LA CERVEZA TERMINADA, TAMBIÉN ES UTILIZADA PARA LA ELABORACIÓN DEL ESTILO MILK STOUT.',33,11,2,133.71),
 (null,' PASTILLAS CARBONATADORAS ',' CONTENIDO 250GR.',34,11,2,81.20),
 (null,'BOTELLA VIDRIO COLOR AMBAR',' BOTELLA DE VIDRIO COLOR AMBAR, VARIAS PRESENTACIONES BOCA PARA TAPA 27MM ',35,12,2,514.61),
 (null,'IRISH MOSS',' Clarificante utilizado en el hervor. Dosis 0,2 gr/L',36,13,2,74.78),
 (null,'PASTILLA WHIRFLOCK','CLARIFICANTE DE HERVIDO. DOSIS 1 PASTILLA CADA 30L.',37,13,2,24.63),
 (null,'ACIDO FOSFORICO ','DISMINUYE EL PH DEL MACERADO, A DIFERENCIA DEL ACIDO LACTICO, SIN AFECTAR EL SABOR DE LA CERVEZA.',47,14,2,770.11),
 (null,'CLORURO DE CALCIO','REDUCE LA ALCALINIDAD DEL AGUA Y ES NUTRIENTE NECESARIO PARA LA LEVADURA.',48,14,2,296.15),
 (null,'YPSUM (SULFATO DE CALCIO)','REDUCE LA ALCALINIDAD DE AGUA Y APORTA NUTRIENTES NECESARIOS PARA LA LEVADURA. RESALTAN EL AMARGOR SECO Y AGUDO CUANDO LOS IBUS SON MUY ELEVADOS.',49,14,2,236.69),
 (null,'ABBAYE LALLEMAND ','LEVADURA SELECCIONADA POR SU CAPACIDAD DE PRODUCIR EXCELENTES CERVEZAS BELGAS, INCLUYENDO CERVEZAS DE ALTA GRAVEDAD COMO DUBBEL, TRIPPEL Y QUEADS.',57,15,2,229.19),
 (null,'BELLE SAISON LALLEMAND','LEVADURA ALE ESTILO-SAISON BELGA.ESTERES Y FENOLES, SABORES Y AROMAS AFRUTADOS, PICANTES Y ESPECIADOS',58,15,2,220.40),
 (null,'BRY LALLEMAND','LEVADURA ALE ESTILO OESTE AMERICANA.ALGUNOS ESTERES, CASI NEUTRA',59,15,2,90.00),
 (null,'ACIDO PERACETICO OXIDIAL ','LPODEROSO BIOCIDAQUE ACTUA EFICIENTEMENTE SOBRE BACTERIAS, HONGOS, LEVADURAS Y ESPORAS.',60,16,2,301.87),
 (null,'ALCOHOL','ALCOHOL 100% AL CUAL SE DEBE BAJAR AL 70% PARA SANITIZAR.',61,16,2,121.00),
 (null,'EPILLO PARA BOTELLA','CEPILLO DE NYLON PARA LIMPIAR LAS BOTELLAS.',62,16,2,92.84),
 (null,'AMARILLO (SELLADO AL VACIO). ','LUPULO PRINCIPALMENTE DE AROMA, CON UN PERFIL CITRICO A POMELO Y FRUTADO.ALFA ÁCIDOS: 7-11%. BETA ÁCIDOS: 5,5-8%.',73,17,2,494.98),
 (null,'APOLLO(SELLADO AL VACIO)','EL APOLLO ES UN LÚPULO DE AMARGOR CON NOTAS HERBALES, ESPECIADO, RESINOSO Y PICANTE. ALFA ÁCIDOS: 15-19%.BETA ÁCIDOS: 5.5-8%.',74,17,2,484.32),
 (null,'CASCADE (SELLADO AL VACIO)','CPUEDE SE USADO PARA BRINDAR AMARGOR, AROMA, TERMINACIÓN Y DRY HOPPING. BRINDA UN LEVE CARACTER CÍTRICO.',75,17,2,223.80),
 (null,'ABBEY WEYERMANN. ','LA MALTA WEYERMANN ABBEY ES UNA MALTA PÁLIDA CARAMELIZADA QUE APORTA UN SABOR FUERTE A PAN COCIDO, NUECES MIEL Y FRUTAS.',86,18,2,201.13),
 (null,'AAVENA ARROLLADA.','LAS CÁSCARAS PROVEEN MASA Y AYUDAN A PREVENIR QUE LA CAMA DE GRANOS SE COMPRIMA Y TAPONE DURANTE EL LAVADO.',87,18,2,171.77),
 (null,'BLACK CASTLE MALTING.','MALTA NEGRA DE 1,300 EBC. LA CEBADA MALTEADA MÁS NEGRA. TORREFACTA A UNA TEMPERATURA DE HASTA 235 °C.',88,18,2,140.68),
 (null,'TAPAS LISAS. ','TAPAS LISAS NEGRAS Y DORADAS 27MM - 100 UNIDADES',94,19,2,216.37),
 (null,'TAPAS LISAS DORADAS','TAPAS LISAS DORADAS 29MM. DORADAS CHAMPAGNE (100 UNIDADES)',95,19,2,506.07),
 (null,'TAPAS IMPRESAS.','TAPAS IMPRESAS 27MM (1000 UNIDADES)',98,19,2,2066.14),
 (null,'KIT ELABORACION BASICO. ','EL KIT CONTIENE LO SIGUIENTE: – OLLA 24 LITROS CON CANILLA Y NIPLE.– FERMENTADOR 20L.– AIRLOCK CON TAPÓN PARA FERMENTADOR.– TERMÓMETRO VIDRIO 0 -110º.',15,20,3,5207.04),
 (null,'TKIT ELABORACION INTERMEDIO','EL KIT CONTIENE LO SIGUIENTE: – OLLA 24 LITROS CON CANILLA Y NIPLE.– FERMENTADOR 20L.– AIRLOCK CON TAPÓN PARA FERMENTADOR.– TERMÓMETRO VIDRIO 0 -110º.',16,20,3,7961.56),
 (null,'KIT ELABORACION PRO','TEL KIT CONTIENE LO SIGUIENTE: – OLLA 24 LITROS CON CANILLA Y NIPLE.– FERMENTADOR 20L.– AIRLOCK CON TAPÓN PARA FERMENTADOR.– TERMÓMETRO VIDRIO 0 -110º.',17,20,3,2066.14),
 (null,'AMBER ALE. ','PILSEN 5 KG. CARAMELO 120L 200 GR. CASCADE 10 GR (AMARGOR). CASCADDE 10GR (AROMA). CLARIFICANTE 3 GR.SAF BE-256.',11,21,3,899.63),
 (null,'DORADA PAMPEANA','KIT DE INSUMOS DE 20 LITROS PARA ELABORAR EL ESTILO DORADA PAMPEANA CON CLARIFICANTE.',12,21,3,609.10),
 (null,'KIT BARLEY WINE','PILSEN. MELANOIDINA.  PALE ALE. CARAMELO 60L. LUPULO CASCADE. CLARIFICANTE. LEVADURA T58. AZUCAR Y CHIPS DE ROBLE.',15,21,3,1312.96);

-- Agrego Provincias
INSERT INTO provincia (id, nombre) VALUES (null, 'Buenos Aires'), (null, 'Catamarca'), (null, 'Chaco'),
(null, 'Chubut'), (null, 'Córdoba'),  (null, 'Corrientes'), (null, 'Entre Rios'), (null, 'Formosa'),
(null, 'Jujuy'), (null, 'La Pampa'), (null, 'La Rioja'), (null, 'Mendoza'), (null, 'Misiones'),
(null, 'Neuquén'), (null, 'Río Negro'), (null, 'Salta'), (null, 'San Juan'), (null, 'San Luis'),
(null, 'Santa Cruz'), (null, 'Santa Fe'), (null, 'Santiago del Estero'), (null, 'Tierra del Fuego'),
(null, 'Tucumán');

-- Agrego Ciudades
INSERT INTO ciudad (id, nombre, provincia_id) VALUES (null, 'La Plata', '1'), (null, 'San Fernando del Valle de Catamarca', '2'),
(null, 'Resistencia', '3'), (null, 'Rawson','4'), (null, 'Córdoba', '5'), (null, 'Unquillo', '5'), (null, 'Villa Allende', '5'),
(null, 'Carlos Paz', '5'), (null, 'Corrientes', '6'), (null, 'Paraná', '7'), (null, 'Formosa', '8'), (null, 'San Salvador de Jujuy', '9'),
(null, 'Santa Rosa', '10'), (null, 'La Rioja', '11'), (null, 'Mendoza', '12'), (null, 'Posadas', '13'), (null, 'Neuquén', '14'),
(null, 'Viedma', '15'), (null, 'Salta', '16'), (null, 'San Juan', '17'), (null, 'San Luis', '18'), (null, 'Río Gallegos', '19'),
(null, 'Santa Fe', '20'), (null, 'Santiago del Estero', '21'),(null, 'Ushuaia', '22'), (null, 'San Miguel de Tucumán', '23');
